const heroIconMap: { [key: string]: string } = {
    "Miya": "https://static.wikia.nocookie.net/mobile-legends/images/8/8c/Hero011-icon.png",
    "Balmond": "https://static.wikia.nocookie.net/mobile-legends/images/9/93/Hero021-icon.png",
    "Saber": "https://static.wikia.nocookie.net/mobile-legends/images/8/87/Hero031-icon.png",
    "Alice": "https://static.wikia.nocookie.net/mobile-legends/images/f/fd/Hero041-icon.png",
    "Nana": "https://static.wikia.nocookie.net/mobile-legends/images/c/c3/Hero051-icon.png",
    "Tigreal": "https://static.wikia.nocookie.net/mobile-legends/images/f/f2/Hero061-icon.png",
    "Alucard": "https://static.wikia.nocookie.net/mobile-legends/images/c/c7/Hero071-icon.png",
    "Karina": "https://static.wikia.nocookie.net/mobile-legends/images/8/8a/Hero081-icon.png",
    "Akai": "https://static.wikia.nocookie.net/mobile-legends/images/b/be/Hero091-icon.png",
    "Franco": "https://static.wikia.nocookie.net/mobile-legends/images/2/25/Hero101-icon.png",
    "Bane": "https://static.wikia.nocookie.net/mobile-legends/images/e/e7/Hero111-icon.png",
    "Bruno": "https://static.wikia.nocookie.net/mobile-legends/images/f/f9/Hero121-icon.png",
    "Clint": "https://static.wikia.nocookie.net/mobile-legends/images/7/73/Hero131-icon.png",
    "Rafaela": "https://static.wikia.nocookie.net/mobile-legends/images/5/5e/Hero141-icon.png",
    "Eudora": "https://static.wikia.nocookie.net/mobile-legends/images/2/2a/Hero151-icon.png",
    "Zilong": "https://static.wikia.nocookie.net/mobile-legends/images/5/5f/Hero161-icon.png",
    "Fanny": "https://static.wikia.nocookie.net/mobile-legends/images/7/78/Hero171-icon.png",
    "Layla": "https://static.wikia.nocookie.net/mobile-legends/images/0/02/Hero181-icon.png",
    "Minotaur": "https://static.wikia.nocookie.net/mobile-legends/images/0/08/Hero191-icon.png",
    "Lolita": "https://static.wikia.nocookie.net/mobile-legends/images/1/17/Hero201-icon.png",
    "Hayabusa": "https://static.wikia.nocookie.net/mobile-legends/images/c/cb/Hero211-icon.png",
    "Freya": "https://static.wikia.nocookie.net/mobile-legends/images/4/4e/Hero221-icon.png",
    "Gord": "https://static.wikia.nocookie.net/mobile-legends/images/2/27/Hero231-icon.png",
    "Natalia": "https://static.wikia.nocookie.net/mobile-legends/images/6/6a/Hero241-icon.png",
    "Kagura": "https://static.wikia.nocookie.net/mobile-legends/images/e/ef/Hero251-icon.png",
    "Chou": "https://static.wikia.nocookie.net/mobile-legends/images/a/a9/Hero261-icon.png",
    "Sun": "https://static.wikia.nocookie.net/mobile-legends/images/f/fe/Hero271-icon.png",
    "Alpha": "https://static.wikia.nocookie.net/mobile-legends/images/3/38/Hero281-icon.png",
    "Ruby": "https://static.wikia.nocookie.net/mobile-legends/images/1/1d/Hero291-icon.png",
    "Yi Sun-shin": "https://static.wikia.nocookie.net/mobile-legends/images/e/ed/Hero301-icon.png",
    "Moskov": "https://static.wikia.nocookie.net/mobile-legends/images/2/2e/Hero311-icon.png",
    "Johnson": "https://static.wikia.nocookie.net/mobile-legends/images/7/73/Hero321-icon.png",
    "Cyclops": "https://static.wikia.nocookie.net/mobile-legends/images/9/96/Hero331-icon.png",
    "Estes": "https://static.wikia.nocookie.net/mobile-legends/images/9/92/Hero341-icon.png",
    "Hilda": "https://static.wikia.nocookie.net/mobile-legends/images/1/11/Hero351-icon.png",
    "Aurora": "https://static.wikia.nocookie.net/mobile-legends/images/2/2c/Hero361-icon.png",
    "Lapu-Lapu": "https://static.wikia.nocookie.net/mobile-legends/images/e/ee/Hero371-icon.png",
    "Vexana": "https://static.wikia.nocookie.net/mobile-legends/images/6/6d/Hero381-icon.png",
    "Roger": "https://static.wikia.nocookie.net/mobile-legends/images/9/97/Hero391-icon.png",
    "Karrie": "https://static.wikia.nocookie.net/mobile-legends/images/d/de/Hero401-icon.png",
    "Gatotkaca": "https://static.wikia.nocookie.net/mobile-legends/images/c/cb/Hero411-icon.png",
    "Harley": "https://static.wikia.nocookie.net/mobile-legends/images/9/92/Hero421-icon.png",
    "Irithel": "https://static.wikia.nocookie.net/mobile-legends/images/5/58/Hero431-icon.png",
    "Grock": "https://static.wikia.nocookie.net/mobile-legends/images/d/dd/Hero441-icon.png",
    "Argus": "https://static.wikia.nocookie.net/mobile-legends/images/c/c7/Hero451-icon.png",
    "Odette": "https://static.wikia.nocookie.net/mobile-legends/images/a/a9/Hero461-icon.png",
    "Lancelot": "https://static.wikia.nocookie.net/mobile-legends/images/2/29/Hero471-icon.png",
    "Diggie": "https://static.wikia.nocookie.net/mobile-legends/images/e/e3/Hero481-icon.png",
    "Hylos": "https://static.wikia.nocookie.net/mobile-legends/images/0/0c/Hero491-icon.png",
    "Zhask": "https://static.wikia.nocookie.net/mobile-legends/images/5/54/Hero501-icon.png",
    "Helcurt": "https://static.wikia.nocookie.net/mobile-legends/images/e/eb/Hero511-icon.png",
    "Pharsa": "https://static.wikia.nocookie.net/mobile-legends/images/e/ef/Hero521-icon.png",
    "Lesley": "https://static.wikia.nocookie.net/mobile-legends/images/8/82/Hero531-icon.png",
    "Jawhead": "https://static.wikia.nocookie.net/mobile-legends/images/1/1c/Hero541-icon.png",
    "Angela": "https://static.wikia.nocookie.net/mobile-legends/images/1/13/Hero551-icon.png",
    "Gusion": "https://static.wikia.nocookie.net/mobile-legends/images/9/94/Hero561-icon.png",
    "Valir": "https://static.wikia.nocookie.net/mobile-legends/images/6/60/Hero571-icon.png",
    "Martis": "https://static.wikia.nocookie.net/mobile-legends/images/a/ac/Hero581-icon.png",
    "Uranus": "https://static.wikia.nocookie.net/mobile-legends/images/b/ba/Hero591-icon.png",
    "Hanabi": "https://static.wikia.nocookie.net/mobile-legends/images/f/ff/Hero601-icon.png",
    "Chang'e": "https://static.wikia.nocookie.net/mobile-legends/images/5/5c/Hero611-icon.png",
    "Kaja": "https://static.wikia.nocookie.net/mobile-legends/images/2/28/Hero621-icon.png",
    "Selena": "https://static.wikia.nocookie.net/mobile-legends/images/d/d4/Hero631-icon.png",
    "Aldous": "https://static.wikia.nocookie.net/mobile-legends/images/9/95/Hero641-icon.png",
    "Claude": "https://static.wikia.nocookie.net/mobile-legends/images/2/29/Hero651-icon.png",
    "Vale": "https://static.wikia.nocookie.net/mobile-legends/images/f/fb/Hero661-icon.png",
    "Leomord": "https://static.wikia.nocookie.net/mobile-legends/images/8/88/Hero671-icon.png",
    "Lunox": "https://static.wikia.nocookie.net/mobile-legends/images/f/f6/Hero681-icon.png",
    "Hanzo": "https://static.wikia.nocookie.net/mobile-legends/images/f/f4/Hero691-icon.png",
    "Belerick": "https://static.wikia.nocookie.net/mobile-legends/images/d/d7/Hero701-icon.png",
    "Kimmy": "https://static.wikia.nocookie.net/mobile-legends/images/1/15/Hero711-icon.png",
    "Thamuz": "https://static.wikia.nocookie.net/mobile-legends/images/1/17/Hero721-icon.png",
    "Harith": "https://static.wikia.nocookie.net/mobile-legends/images/5/5a/Hero731-icon.png",
    "Minsitthar": "https://static.wikia.nocookie.net/mobile-legends/images/1/1e/Hero741-icon.png",
    "Kadita": "https://static.wikia.nocookie.net/mobile-legends/images/4/46/Hero751-icon.png",
    "Faramis": "https://static.wikia.nocookie.net/mobile-legends/images/3/34/Hero761-icon.png",
    "Badang": "https://static.wikia.nocookie.net/mobile-legends/images/a/a4/Hero771-icon.png",
    "Khufra": "https://static.wikia.nocookie.net/mobile-legends/images/c/cd/Hero781-icon.png",
    "Granger": "https://static.wikia.nocookie.net/mobile-legends/images/7/7c/Hero791-icon.png",
    "Guinevere": "https://static.wikia.nocookie.net/mobile-legends/images/f/f1/Hero801-icon.png",
    "Esmeralda": "https://static.wikia.nocookie.net/mobile-legends/images/8/88/Hero811-icon.png",
    "Terizla": "https://static.wikia.nocookie.net/mobile-legends/images/a/ab/Hero821-icon.png",
    "X.Borg": "https://static.wikia.nocookie.net/mobile-legends/images/7/7a/Hero831-icon.png",
    "Ling": "https://static.wikia.nocookie.net/mobile-legends/images/c/ca/Hero841-icon.png",
    "Dyrroth": "https://static.wikia.nocookie.net/mobile-legends/images/6/62/Hero851-icon.png",
    "Lylia": "https://static.wikia.nocookie.net/mobile-legends/images/a/a4/Hero861-icon.png",
    "Baxia": "https://static.wikia.nocookie.net/mobile-legends/images/0/09/Hero871-icon.png",
    "Masha": "https://static.wikia.nocookie.net/mobile-legends/images/c/c5/Hero881-icon.png",
    "Wanwan": "https://static.wikia.nocookie.net/mobile-legends/images/2/24/Hero891-icon.png",
    "Silvanna": "https://static.wikia.nocookie.net/mobile-legends/images/4/40/Hero901-icon.png",
    "Cecilion": "https://static.wikia.nocookie.net/mobile-legends/images/8/85/Hero911-icon.png",
    "Carmilla": "https://static.wikia.nocookie.net/mobile-legends/images/2/23/Hero921-icon.png",
    "Atlas": "https://static.wikia.nocookie.net/mobile-legends/images/6/6e/Hero931-icon.png",
    "Popol and Kupa": "https://static.wikia.nocookie.net/mobile-legends/images/a/ab/Hero941-icon.png",
    "Yu Zhong": "https://static.wikia.nocookie.net/mobile-legends/images/5/53/Hero951-icon.png",
    "Luo Yi": "https://static.wikia.nocookie.net/mobile-legends/images/f/f0/Hero961-icon.png",
    "Benedetta": "https://static.wikia.nocookie.net/mobile-legends/images/4/47/Hero971-icon.png",
    "Khaleed": "https://static.wikia.nocookie.net/mobile-legends/images/d/d2/Hero981-icon.png",
    "Barats": "https://static.wikia.nocookie.net/mobile-legends/images/1/1a/Hero991-icon.png",
    "Brody": "https://static.wikia.nocookie.net/mobile-legends/images/1/12/Hero1001-icon.png",
    "Yve": "https://static.wikia.nocookie.net/mobile-legends/images/c/cd/Hero1011-icon.png",
    "Mathilda": "https://static.wikia.nocookie.net/mobile-legends/images/c/cf/Hero1021-icon.png",
    "Paquito": "https://static.wikia.nocookie.net/mobile-legends/images/3/35/Hero1031-icon.png",
    "Gloo": "https://static.wikia.nocookie.net/mobile-legends/images/4/45/Hero1041-icon.png",
    "Beatrix": "https://static.wikia.nocookie.net/mobile-legends/images/a/a9/Hero1051-icon.png",
    "Phoveus": "https://static.wikia.nocookie.net/mobile-legends/images/8/88/Hero1061-icon.png",
    "Natan": "https://static.wikia.nocookie.net/mobile-legends/images/2/25/Hero1071-icon.png",
    "Aulus": "https://static.wikia.nocookie.net/mobile-legends/images/b/bf/Hero1081-icon.png",
    "Aamon": "https://static.wikia.nocookie.net/mobile-legends/images/b/bc/Hero1091-icon.png",
    "Valentina": "https://static.wikia.nocookie.net/mobile-legends/images/6/62/Hero1101-icon.png",
    "Edith": "https://static.wikia.nocookie.net/mobile-legends/images/3/36/Hero1111-icon.png",
    "Floryn": "https://static.wikia.nocookie.net/mobile-legends/images/2/20/Hero1121-icon.png",
    "Yin": "https://static.wikia.nocookie.net/mobile-legends/images/b/b5/Hero1131-icon.png",
    "Melissa": "https://static.wikia.nocookie.net/mobile-legends/images/0/09/Hero1141-icon.png",
    "Xavier": "https://static.wikia.nocookie.net/mobile-legends/images/8/80/Hero1151-icon.png",
    "Julian": "https://static.wikia.nocookie.net/mobile-legends/images/c/c2/Hero1161-icon.png",
    "Fredrinn": "https://static.wikia.nocookie.net/mobile-legends/images/f/f4/Hero1171-icon.png",
    "Joy": "https://static.wikia.nocookie.net/mobile-legends/images/c/c1/Hero1181-icon.png",
    "Novaria": "https://static.wikia.nocookie.net/mobile-legends/images/a/a1/Hero1191-icon.png",
    "Arlott": "https://static.wikia.nocookie.net/mobile-legends/images/2/22/Hero1201-icon.png",
    "Ixia": "https://static.wikia.nocookie.net/mobile-legends/images/a/a2/Hero1211-icon.png",
    "Nolan": "https://static.wikia.nocookie.net/mobile-legends/images/e/e1/Hero1221-icon.png",
    "Cici": "https://static.wikia.nocookie.net/mobile-legends/images/6/65/Hero1231-icon.png",
    "Chip": "https://static.wikia.nocookie.net/mobile-legends/images/9/94/Hero1241-icon.png",
    "Zhuxin": "https://static.wikia.nocookie.net/mobile-legends/images/0/05/Hero1251-icon.png",
    "Suyou": "https://static.wikia.nocookie.net/mobile-legends/images/c/c4/Hero1261-icon.png",
    "Lukas": "https://static.wikia.nocookie.net/mobile-legends/images/1/1c/Hero1271-icon.png",
    "Kalea": "https://static.wikia.nocookie.net/mobile-legends/images/5/56/Hero1281-icon.png",
    "Zetian": "https://static.wikia.nocookie.net/mobile-legends/images/5/5c/Hero1291-icon.png"
    
};


const CLOUDIMG_PREFIX = "https://ce880219c.cloudimg.io/v7/";
const CLOUDIMG_CROP = "?width=500&height=500&func=face&face_margin=60";

function withCloudImg(url: string) {
  // Jika url sudah mengandung prefix, jangan tambahkan lagi
  if (url.startsWith(CLOUDIMG_PREFIX)) return url;
  return CLOUDIMG_PREFIX + url.replace(/^https?:\/\//, "");
}

function withCloudImgCrop(url: string) {
  // Hilangkan query string lama jika ada
  let cleanUrl = url.split("?")[0];
  return withCloudImg(cleanUrl) + CLOUDIMG_CROP;
}

const heroMap: { [key: string]: string } = {
    "Aamon":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/7/72/Aamon_infobox.jpg/600px-Aamon_infobox.jpg"),
    "Akai":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/2/20/Akai_infobox.jpg/600px-Akai_infobox.jpg"),
    "Aldous":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/6/64/Aldous_infobox.jpg/600px-Aldous_infobox.jpg"),
    "Alice":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/0/0e/Alice_infobox.jpg/600px-Alice_infobox.jpg"),
    "Alpha":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/c/c0/Alpha_infobox.jpg/600px-Alpha_infobox.jpg"),
    "Alucard":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/d/d5/Alucard_infobox.jpg/600px-Alucard_infobox.jpg"),
    "Angela":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/f/f0/Angela_infobox.jpg/600px-Angela_infobox.jpg"),
    "Argus":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/e/e4/Argus_infobox.jpg/600px-Argus_infobox.jpg"),
    "Arlott":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/a/ad/Arlott_infobox.jpg/600px-Arlott_infobox.jpg"),
    "Atlas":  withCloudImgCrop("https://ik.imagekit.io/sadapphone/hero_mlbb/Atlas_.jpg?updatedAt=1752476822900"),
    "Aulus":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/4/48/Aulus_infobox.jpg/600px-Aulus_infobox.jpg"),
    "Aurora":  withCloudImgCrop("https://liquipedia.net/commons/images/6/65/Aurora_infobox.png"),
    "Badang":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/5/53/Badang_infobox.jpg/600px-Badang_infobox.jpg"),
    "Balmond":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/8/86/Balmond_infobox.jpg/600px-Balmond_infobox.jpg"),
    "Bane":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/e/e9/Bane_Frozen_King.jpg/600px-Bane_Frozen_King.jpg"),
    "Barats":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/8/8a/Barats_infobox.jpg/600px-Barats_infobox.jpg"),
    "Baxia":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/d/d5/Baxia_Infobox.jpg/600px-Baxia_Infobox.jpg"),
    "Beatrix":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/4/4a/Beatrix_infobox.jpg/600px-Beatrix_infobox.jpg"),
    "Belerick":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/b/b2/Belerick_Infobox.jpg/600px-Belerick_Infobox.jpg"),
    "Benedetta":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/7/79/Benedetta_infobox.jpg/600px-Benedetta_infobox.jpg"),
    "Brody":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/9/93/Brody_infobox.jpg/600px-Brody_infobox.jpg"),
    "Bruno":  withCloudImgCrop("https://liquipedia.net/commons/images/c/c6/Bruno_infobox.jpg"),
    "Carmilla":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/a/a4/Carmilla_infobox.jpg/600px-Carmilla_infobox.jpg"),
    "Cecilion":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/8/84/Cecilion_infobox.jpg/600px-Cecilion_infobox.jpg"),
    "Chang'e":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/5/51/Chang%27e_infobox.jpg/600px-Chang%27e_infobox.jpg"),
    "Chip":  withCloudImgCrop("https://liquipedia.net/commons/images/3/37/Chip_infobox.jpg"),
    "Chou":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/c/c0/Chou_Infobox.jpg/600px-Chou_Infobox.jpg"),
    "Cici":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/a/a1/Cici_infobox.jpg/600px-Cici_infobox.jpg"),
    "Claude":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/a/a3/Claude_infobox.jpg/600px-Claude_infobox.jpg"),
    "Clint":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/9/90/Clint_Infobox.jpg/600px-Clint_Infobox.jpg"),
    "Cyclops":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/1/10/Cyclops_infobox.jpg/600px-Cyclops_infobox.jpg"),
    "Diggie":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/b/b9/Diggie_infobox.png/600px-Diggie_infobox.png"),
    "Dyrroth":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/2/2e/Dyrroth_infobox.jpg/600px-Dyrroth_infobox.jpg"),
    "Edith":  withCloudImgCrop("https://liquipedia.net/commons/images/d/d8/Edith_infobox.jpg"),
    "Esmeralda":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/b/bb/Esmeralda_infobox.jpg/600px-Esmeralda_infobox.jpg"),
    "Estes":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/0/0a/Estes_infobox.png/600px-Estes_infobox.png"),
    "Eudora":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/9/92/Eudora_infobox.jpg/600px-Eudora_infobox.jpg"),
    "Fanny":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/8/86/Fanny_infobox.jpg/600px-Fanny_infobox.jpg"),
    "Faramis":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/5/53/Faramis_infobox.jpg/600px-Faramis_infobox.jpg"),
    "Floryn":  withCloudImgCrop("https://liquipedia.net/commons/images/4/40/Floryn_infobox.jpg"),
    "Franco":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/a/aa/Franco_infobox.jpg/600px-Franco_infobox.jpg"),
    "Fredrinn":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/b/bf/Fredrinn_infobox.jpg/600px-Fredrinn_infobox.jpg"),
    "Freya":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/b/b2/Freya_infobox.jpg/600px-Freya_infobox.jpg"),
    "Gatotkaca":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/4/46/Gatotkaca_Infobox.jpg/600px-Gatotkaca_Infobox.jpg"),
    "Gloo":  withCloudImgCrop("https://liquipedia.net/commons/images/0/04/Gloo_Infobox.jpg"),
    "Gord":  withCloudImgCrop("https://static.wikia.nocookie.net/mobile-legends/images/1/1a/Gord_%28Professor_of_the_Mystics%29.jpg/revision/latest/scale-to-width-down/1000?cb=20241128083520"),
    "Granger":  withCloudImgCrop("https://pm1.aminoapps.com/7296/b7be52c43fc9a5de15bedfbb99222e3f304c2390r1-606-680v2_00.jpg"),
    "Grock":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/d/d0/Grock_Infobox.jpg/600px-Grock_Infobox.jpg"),
    "Guinevere":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/7/77/Guinevere_infobox.jpg/600px-Guinevere_infobox.jpg"),
    "Gusion":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/4/46/Gusion_infobox.jpg/600px-Gusion_infobox.jpg"),
    "Hanabi":  withCloudImgCrop("https://liquipedia.net/commons/images/4/41/Hanabi_infobox.jpg"),
    "Hanzo":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/d/dc/Hanzo_infobox.jpg/600px-Hanzo_infobox.jpg"),
    "Harith":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/b/b0/Harith_infobox.jpg/600px-Harith_infobox.jpg"),
    "Harley":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/4/4a/Harley_infobox.png/600px-Harley_infobox.png"),
    "Hayabusa":  withCloudImgCrop("https://liquipedia.net/commons/images/3/36/Hayabusa_infobox.jpg"),
    "Helcurt":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/2/24/Helcurt_infobox.jpg/600px-Helcurt_infobox.jpg"),
    "Hilda":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/d/d4/Hilda_infobox.jpg/600px-Hilda_infobox.jpg"),
    "Hylos":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/0/08/Hylos_Infobox.jpg/600px-Hylos_Infobox.jpg"),
    "Irithel":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/b/ba/Irithel_infobox.png/600px-Irithel_infobox.png"),
    "Ixia":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/0/00/Ixia_infobox.jpg/600px-Ixia_infobox.jpg"),
    "Jawhead":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/0/06/Jawhead_infobox.jpg/600px-Jawhead_infobox.jpg"),
    "Johnson":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/6/6c/Johnson_Infobox.jpg/600px-Johnson_Infobox.jpg"),
    "Joy":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/8/83/Joy_infobox.jpg/600px-Joy_infobox.jpg"),
    "Julian":  withCloudImgCrop("https://cdn.oneesports.gg/cdn-data/2024/02/MLBB_Julian.jpg"),
    "Kadita":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/9/99/Kadita_infobox.jpg/600px-Kadita_infobox.jpg"),
    "Kagura":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/5/51/Kagura_infobox.jpg/600px-Kagura_infobox.jpg"),
    "Kaja":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/1/1a/Kaja_infobox.jpg/600px-Kaja_infobox.jpg"),
    "Kalea":  withCloudImgCrop("https://static.wikia.nocookie.net/mobile-legends/images/9/9a/Hero1281-portrait.png/revision/latest?cb=20250407160846"),
    "Karina":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/9/96/Karina_infobox.jpg/600px-Karina_infobox.jpg"),
    "Karrie":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/6/6c/Karrie_infobox.png/600px-Karrie_infobox.png"),
    "Khaleed":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/3/35/Khaleed_infobox.jpg/600px-Khaleed_infobox.jpg"),
    "Khufra":  withCloudImgCrop("https://ik.imagekit.io/sadapphone/hero_mlbb/khufra.jpg?updatedAt=1752474139488"),
    "Kimmy":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/3/37/Kimmy_infobox.jpg/600px-Kimmy_infobox.jpg"),
    "Lancelot":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/0/08/Lancelot_infobox.jpg/600px-Lancelot_infobox.jpg"),
    "Lapu-Lapu":  withCloudImgCrop("https://liquipedia.net/commons/images/2/24/Lapu-lapu_infobox.png"),
    "Layla":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/5/56/Layla_Energy_Gunner.png/600px-Layla_Energy_Gunner.png"),
    "Leomord":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/2/2e/Leomord_infobox.jpg/600px-Leomord_infobox.jpg"),
    "Lesley":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/b/b1/Lesley_infobox.jpg/600px-Lesley_infobox.jpg"),
    "Ling":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/9/9a/Ling_infobox.jpg/600px-Ling_infobox.jpg"),
    "Lolita":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/c/ce/Lolita_infobox.jpg/600px-Lolita_infobox.jpg"),
    "Lukas":  withCloudImgCrop("https://ik.imagekit.io/sadapphone/hero_mlbb/Lukas.webp"),
    "Lunox":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/7/79/Lunox_infobox.jpg/600px-Lunox_infobox.jpg"),
    "Luo Yi":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/e/e0/Luo_Yi_infobox.jpg/600px-Luo_Yi_infobox.jpg"),
    "Lylia":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/c/c2/Lylia_infobox.jpg/600px-Lylia_infobox.jpg"),
    "Martis":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/b/b2/Martis_infobox.jpg/600px-Martis_infobox.jpg"),
    "Masha":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/a/a3/Masha_infobox.jpg/600px-Masha_infobox.jpg"),
    "Mathilda":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/d/df/Mathilda_infobox.jpg/600px-Mathilda_infobox.jpg"),
    "Melissa":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/7/72/Melissa_infobox.jpg/600px-Melissa_infobox.jpg"),
    "Minotaur":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/f/f6/Minotaur_infobox.jpg/600px-Minotaur_infobox.jpg"),
    "Minsitthar":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/6/67/Minsitthar_infobox.jpg/600px-Minsitthar_infobox.jpg"),
    "Miya":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/b/be/Miya_infobox.jpg/600px-Miya_infobox.jpg"),
    "Moskov":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/a/af/Moskov_Infobox.jpg/600px-Moskov_Infobox.jpg"),
    "Nana":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/2/2c/Nana_infobox.jpg/600px-Nana_infobox.jpg"),
    "Natalia":  withCloudImgCrop("https://i.pinimg.com/736x/5d/9f/2b/5d9f2b66c75943a82709b71be0e7e2b8.jpg"),
    "Natan":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/3/30/Natan_infobox.jpg/600px-Natan_infobox.jpg"),
    "Nolan":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/6/60/Nolan_infobox.jpeg/600px-Nolan_infobox.jpeg"),
    "Novaria":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/e/ee/Novaria_infobox.jpg/600px-Novaria_infobox.jpg"),
    "Odette":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/8/87/Odette_infobox.png/600px-Odette_infobox.png"),
    "Paquito":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/1/1f/Paquito_infobox.jpg/600px-Paquito_infobox.jpg"),
    "Pharsa":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/4/46/Pharsa_Infobox.jpg/600px-Pharsa_Infobox.jpg"),
    "Phoveus":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/a/a1/Phoveus_infobox.jpg/600px-Phoveus_infobox.jpg"),
    "Popol and Kupa":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/5/5d/Popol_and_Kupa_infobox.jpg/600px-Popol_and_Kupa_infobox.jpg"),
    "Rafaela":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/7/7b/Rafaela_infobox.jpg/600px-Rafaela_infobox.jpg"),
    "Roger":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/c/c4/Roger_infobox.png/600px-Roger_infobox.png"),
    "Ruby":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/8/8b/Ruby_infobox.jpeg/600px-Ruby_infobox.jpeg"),
    "Saber":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/3/37/Saber_infobox.jpg/600px-Saber_infobox.jpg"),
    "Selena":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/a/a0/Selena_infobox.jpg/600px-Selena_infobox.jpg"),
    "Silvanna":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/0/06/Silvanna_infobox.jpg/600px-Silvanna_infobox.jpg"),
    "Sun":  withCloudImgCrop("https://liquipedia.net/commons/images/d/da/Sun_Monkey_King.png"),
    "Suyou":  withCloudImgCrop("https://liquipedia.net/commons/images/0/04/Suyou_infobox.png"),
    "Terizla":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/3/3d/Terizla_infobox.jpg/600px-Terizla_infobox.jpg"),
    "Thamuz":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/c/c8/Thamuz_infobox.jpg/600px-Thamuz_infobox.jpg"),
    "Tigreal":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/e/e7/Tigreal_infobox.jpg/600px-Tigreal_infobox.jpg"),
    "Uranus":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/a/a6/Uranus_Infobox.jpg/600px-Uranus_Infobox.jpg"),
    "Vale":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/3/3e/Vale_infobox.jpg/600px-Vale_infobox.jpg"),
    "Valentina":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/7/75/Valentina_infobox.jpg/600px-Valentina_infobox.jpg"),
    "Valir":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/b/b6/Valir_infobox.jpg/600px-Valir_infobox.jpg"),
    "Vexana":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/2/2a/Vexana_infobox.jpg/600px-Vexana_infobox.jpg"),
    "Wanwan":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/4/4d/Wanwan_infobox.jpg/600px-Wanwan_infobox.jpg"),
    "X.Borg":  withCloudImgCrop("https://liquipedia.net/commons/images/a/ad/X.Borg_infobox.jpg"),
    "Xavier":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/f/f2/Xavier_infobox.jpg/600px-Xavier_infobox.jpg"),
    "Yi Sun-shin":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/7/7e/Yi_Sun-Shin_infobox.jpg/600px-Yi_Sun-Shin_infobox.jpg"),
    "Yin":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/2/25/Yin_infobox.jpg/600px-Yin_infobox.jpg"),
    "Yu Zhong":  withCloudImgCrop("https://liquipedia.net/commons/images/thumb/9/9c/Yu_Zhong_infobox.jpg/600px-Yu_Zhong_infobox.jpg"),
    "Yve":  withCloudImgCrop("https://static.wikia.nocookie.net/character-stats-and-profiles/images/0/0c/Yve_%28MLBB%29.webp/revision/latest?cb=20241114040954"),
    "Zetian":  withCloudImgCrop("https://liquipedia.net/commons/images/0/08/Zetian_infobox.png"),
    "Zhask":  withCloudImgCrop("https://cdn.oneesports.gg/cdn-data/2022/02/MLBB_Zhask-1.jpg"),
    "Zhuxin":  withCloudImgCrop("https://liquipedia.net/commons/images/3/34/Zhuxin_infobox.jpg"),
    "Zilong":  withCloudImgCrop("https://liquipedia.net/commons/images/7/7d/Zilong_Spear_of_Dragon.png")
  
};






export const herosIcon = (heroName: string): string => {
    return heroIconMap[heroName] || ''; // Return empty string if hero not found
};


export const heros = (heroName: string): string => {
  return heroMap[heroName] || ''; // Return empty string if hero not found
};